export enum ENVEnum {
  NODE_ENV = "NODE_ENV",
  DATABASE_URL = "DATABASE_URL",

  PORT = "PORT",
  BASE_URL = "BASE_URL",

  JWT_SECRET = "JWT_SECRET",
  JWT_EXPIRES_IN = "JWT_EXPIRES_IN",

  MAIL_USER = "MAIL_USER",
  MAIL_PASS = "MAIL_PASS",

  SUPER_ADMIN_EMAIL = "SUPER_ADMIN_EMAIL",
  SUPER_ADMIN_PASS = "SUPER_ADMIN_PASS",

  REDIS_URL = "REDIS_URL",
  REDIS_HOST = "REDIS_HOST",
  REDIS_PASS = "REDIS_PASS",
  REDIS_USER = "REDIS_USER",
  REDIS_PORT = "REDIS_PORT",

  TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID",
  TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN",
  TWILIO_PHONE_NUMBER = "TWILIO_PHONE_NUMBER",

  // aws
  AWS_REGION = "AWS_REGION",
  AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID",
  AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY",
  AWS_S3_BUCKET_NAME = "AWS_S3_BUCKET_NAME"
}
