name: "Setup SSH"
description: "Sets up SSH for deployment"
runs:
    using: "composite"
    steps:
        - name: Setup SSH 🔐
          shell: bash
          run: |
              mkdir -p ~/.ssh
              chmod 700 ~/.ssh
              echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
              chmod 600 ~/.ssh/deploy_key
              ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
              chmod 644 ~/.ssh/known_hosts
              cat > ~/.ssh/config <<EOF
              Host deploy-server
                HostName ${{ secrets.VPS_HOST }}
                User ${{ secrets.VPS_USER }}
                IdentityFile ~/.ssh/deploy_key
                StrictHostKeyChecking no
              EOF
              chmod 600 ~/.ssh/config
        - name: Test SSH Connection ✅
          shell: bash
          run: |
              ssh deploy-server "echo '🎉 SSH Connected Successfully!'"
