import { ApiProperty, IntersectionType, PartialType } from "@nestjs/swagger";

class PostsMetricsDto {
    @ApiProperty({
        description: "Post ID",
        example: "uuid",
    })
    postId: string;

    @ApiProperty({
        description: "Total number of likes",
        example: 10,
    })
    totalLikes?: number;

    @ApiProperty({
        description: "Total number of comments",
        example: 10,
    })
    totalComments?: number;

    @ApiProperty({
        description: "Total number of shares",
        example: 10,
    })
    totalShares?: number;

    @ApiProperty({
        description: "Total number of views",
        example: 10,
    })
    totalViews?: number;

    @ApiProperty({
        description: "Revenue generated by this post",
        example: 10.0,
    })
    revenueGenerated?: number;

    @ApiProperty({
        description: "Date when the metrics were last updated",
        example: "2023-01-01T00:00:00.000Z",
    })
    lastUpdated?: string;
}
export class CreatePostsMetricsDto extends IntersectionType(PostsMetricsDto) {}
export class UpdatePostsMetricsDto extends IntersectionType(PartialType(PostsMetricsDto)) {}
