import { Comment, Community, PostEvent, UserRegistration } from "./events-payload";

// 🚀 EVENT TYPE CONSTANTS (All in UPPERCASE for consistency)
export const EVENT_TYPES = {
    COMMUNITY_CREATE: "COMMUNITY_CREATE",
    COMMUNITY_UPDATE: "COMMUNITY_UPDATE",
    COMMUNITY_DELETE: "COMMUNITY_DELETE",

    COMMENT_CREATE: "COMMENT_CREATE",
    COMMENT_UPDATE: "COMMENT_UPDATE",
    COMMENT_DELETE: "COMMENT_DELETE",

    USERREGISTRATION_CREATE: "USERREGISTRATION_CREATE",
    USERREGISTRATION_UPDATE: "USERREGISTRATION_UPDATE",
    USERREGISTRATION_DELETE: "USERREGISTRATION_DELETE",

    POST_CREATE: "POST_CREATE",
    POST_UPDATE: "POST_UPDATE",
    POST_DELETE: "POST_DELETE",

    MESSAGE_CREATE: "MESSAGE_CREATE",
} as const;

// Type-safe keys for autocomplete
export type EventType = keyof typeof EVENT_TYPES;

//  Event payload mapping for type safety
export type EventPayloadMap = {
    [EVENT_TYPES.COMMUNITY_CREATE]: Community;
    [EVENT_TYPES.COMMUNITY_UPDATE]: Community;
    [EVENT_TYPES.COMMUNITY_DELETE]: Community;

    [EVENT_TYPES.COMMENT_CREATE]: Comment;
    [EVENT_TYPES.COMMENT_UPDATE]: Comment;
    [EVENT_TYPES.COMMENT_DELETE]: Comment;

    [EVENT_TYPES.USERREGISTRATION_CREATE]: UserRegistration;
    [EVENT_TYPES.USERREGISTRATION_UPDATE]: UserRegistration;
    [EVENT_TYPES.USERREGISTRATION_DELETE]: UserRegistration;

    [EVENT_TYPES.POST_CREATE]: PostEvent;
    [EVENT_TYPES.POST_UPDATE]: PostEvent;
    [EVENT_TYPES.POST_DELETE]: PostEvent;

    [EVENT_TYPES.MESSAGE_CREATE]?: any;
};
