name: "Setup and Load Environment"
description: "Generates .env from secrets and exports to GITHUB_ENV"

runs:
  using: "composite"
  steps:
    - name: Generate .env file
      shell: bash
      run: |
        cat <<EOF > .env
        DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
        PACKAGE_NAME=${{ secrets.PACKAGE_NAME }}
        PACKAGE_VERSION=${{ secrets.PACKAGE_VERSION }}
        EMAIL=${{ secrets.EMAIL }}

        NODE_ENV="production"

        PG_USERNAME=${{ secrets.PG_USERNAME }}
        PG_PASSWORD=${{ secrets.PG_PASSWORD }}
        PG_DATABASE=${{ secrets.PG_DATABASE }}
        PG_PORT=${{ secrets.PG_PORT }}
        DATABASE_URL=${{ secrets.DATABASE_URL }}

        JWT_SECRET=${{ secrets.JWT_SECRET }}
        JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
        BASE_URL=${{ secrets.BASE_URL }}

        PORT=${{ secrets.PORT }}

        MAIL_USER=${{ secrets.MAIL_USER }}
        MAIL_PASS=${{ secrets.MAIL_PASS }}

        SUPER_ADMIN_EMAIL=${{ secrets.SUPER_ADMIN_EMAIL }}
        SUPER_ADMIN_PASS=${{ secrets.SUPER_ADMIN_PASS }}

        REDIS_HOST=${{ secrets.REDIS_HOST }}
        REDIS_USER=${{ secrets.REDIS_USER }}
        REDIS_PASS=${{ secrets.REDIS_PASS }}
        REDIS_PORT=${{ secrets.REDIS_PORT }}
        REDIS_CONTAINER=${{ secrets.REDIS_CONTAINER }}
        REDIS_URL=${{ secrets.REDIS_URL }}

        TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}

        AWS_REGION=${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}

        IMAGE_TAG=${{ secrets.IMAGE_TAG }}
        DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
        GIT_TOKEN=${{ secrets.GIT_TOKEN }}
        VPS_HOST=${{ secrets.VPS_HOST }}
        VPS_USER=${{ secrets.VPS_USER }}
        VPS_SSH_PRIVATE_KEY=${{ secrets.VPS_SSH_PRIVATE_KEY }}
        EOF

    - name: Export .env to GITHUB_ENV
      shell: bash
      run: |
        while IFS='=' read -r key value; do
          if [[ ! "$key" =~ ^# && -n "$key" ]]; then
            echo "$key=$value" >> "$GITHUB_ENV"
          fi
        done < .env

    - name: Verify setup (without exposing values)
      shell: bash
      run: |
        echo "🤝 .env generated and loaded into environment (total vars: $(grep -c '=' .env))"
